/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_de_denuncias;

import Conexion.BD_Querys;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vallecillo
 */
public  class frmDatosPresuntoAutor extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDatosPresuntoAutor
     */
    public frmDatosPresuntoAutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tb_Cicatrices = new javax.swing.JTextField();
        Tb_Estatura = new javax.swing.JTextField();
        Tb_Tatuajes = new javax.swing.JTextField();
        Tb_Nombre = new javax.swing.JTextField();
        Tb_Alias = new javax.swing.JTextField();
        Bt_Cabello = new javax.swing.JComboBox<String>();
        Bt_color_de_piel = new javax.swing.JComboBox<String>();
        Cb_Contextura = new javax.swing.JComboBox<String>();
        Cb_Sexo = new javax.swing.JComboBox<String>();
        Bt_Aceptar = new javax.swing.JButton();
        Bt_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ta_Descripciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Presunto Autor");
        setBackground(new java.awt.Color(153, 153, 255));
        setName("Datos del presunto autor"); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("Alias:");

        jLabel3.setText("Sexo:");

        jLabel4.setText("Color de piel:");

        jLabel5.setText("Cabello");

        jLabel6.setText("Estatura Aprox..(mts)");

        jLabel7.setText("Contextura");

        jLabel8.setText("Tatuajes");

        jLabel9.setText("Cicatrices");

        jLabel10.setText("Otras descripciones");

        Bt_Cabello.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Liso", "Crespo", "Ondulado", "Chirizo" }));

        Bt_color_de_piel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Tipo I Blanco", "Tipo II Blanco", "Tipo III color beige", "Tipo IV color beige", "Tipo V color marrón oscuro", "Tipo VI Negro" }));

        Cb_Contextura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Recio", "Delgado", "Gordo" }));

        Cb_Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Masculino", "Femenino" }));

        Bt_Aceptar.setText("Aceptar");
        Bt_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AceptarActionPerformed(evt);
            }
        });

        Bt_Cancelar.setText("Cancelar");
        Bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_CancelarActionPerformed(evt);
            }
        });

        Ta_Descripciones.setColumns(20);
        Ta_Descripciones.setRows(5);
        jScrollPane1.setViewportView(Ta_Descripciones);
        Ta_Descripciones.getAccessibleContext().setAccessibleName("TbDescripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(98, 98, 98)
                        .addComponent(Tb_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(Tb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(96, 96, 96)
                        .addComponent(Cb_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(61, 61, 61)
                        .addComponent(Bt_color_de_piel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(89, 89, 89)
                        .addComponent(Bt_Cabello, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(69, 69, 69)
                        .addComponent(Cb_Contextura, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(82, 82, 82)
                        .addComponent(Tb_Tatuajes, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(78, 78, 78)
                        .addComponent(Tb_Cicatrices, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bt_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Tb_Estatura, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(Tb_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(Tb_Alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(Cb_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(Bt_color_de_piel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(Bt_Cabello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(Tb_Estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(Cb_Contextura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(Tb_Tatuajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(Tb_Cicatrices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Nombre");
        Tb_Cicatrices.getAccessibleContext().setAccessibleName("TbCicatrices");
        Tb_Estatura.getAccessibleContext().setAccessibleName("TbEstaturaAprox");
        Tb_Tatuajes.getAccessibleContext().setAccessibleName("TbTatuajes");
        Tb_Nombre.getAccessibleContext().setAccessibleName("tbNombrePresuntoAutor");
        Tb_Alias.getAccessibleContext().setAccessibleName("tbAliasPresuntoAutor");
        Bt_Aceptar.getAccessibleContext().setAccessibleName("BtAceptar");
        Bt_Cancelar.getAccessibleContext().setAccessibleName("BtCancelar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_CancelarActionPerformed
      this.dispose();
    }//GEN-LAST:event_Bt_CancelarActionPerformed

    private void Bt_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AceptarActionPerformed
       
                String nombre=Tb_Nombre.getText();
                String alias=Tb_Alias.getText();
                String sexo=Cb_Sexo.getToolTipText();
                String color_de_piel=Bt_color_de_piel.getToolTipText();
                String cabello=Bt_Cabello.getToolTipText();
                float estatura= Float.valueOf( Tb_Estatura.getText());
                String contextura=Cb_Contextura.getToolTipText();
                String tatuajes=Tb_Tatuajes.getText();
                String cicatrices=Tb_Cicatrices.getText();
                String descripciones=Ta_Descripciones.getText();
                int id=1;
                int ide=6;
          if (nombre==null || alias.equals("") || sexo.equals("") || color_de_piel.equals("") ||cabello.equals("")  || contextura.equals("") || tatuajes.equals("") ||cicatrices.equals("") || descripciones.equals("") ){
                        
                        JOptionPane.showMessageDialog(null,"Porfavor ingrese todos los datos");
                        
                    } else{
                int retorno;
                ArrayList<ArrayList<String>> datos;
                String consul="select LAST_INSERT_ID () from  " ; 
                datos = Conexion.ejecutar_consulta(consul);
                 datos.get(0);
                 JOptionPane.showMessageDialog(null,datos.get(0));
                
                String insertar = "insert into presuntoautor values("+null+",'"+nombre+"','"+descripciones+"',"
                        + "'"+color_de_piel+"','"+estatura+"','"+cabello+"','"+contextura+"','"+tatuajes+"',"
                        + "'"+cicatrices+"','"+sexo+"','"+alias+"','"+ide+"');";
            
            retorno = Conexion.ejecutar_comando(insertar);
               if(retorno==0){
               JOptionPane.showMessageDialog(null,"No se han insertado correctamente los datos ");
            } else{
                   Tb_Nombre.setText("");
                   Tb_Cicatrices.setText("");
                   Tb_Tatuajes.setText("");
                   Ta_Descripciones.setText("");
                   Tb_Alias.setText("");
                    Tb_Estatura.setText("");
                JOptionPane.showMessageDialog(null,"Se han insertado los datos correctamente  ");
            }
          frmPersona   persona = new frmPersona();
        this.getDesktopPane().add(persona);
        persona.show();
          
          }      
    }//GEN-LAST:event_Bt_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Aceptar;
    private javax.swing.JComboBox<String> Bt_Cabello;
    private javax.swing.JButton Bt_Cancelar;
    private javax.swing.JComboBox<String> Bt_color_de_piel;
    private javax.swing.JComboBox<String> Cb_Contextura;
    private javax.swing.JComboBox<String> Cb_Sexo;
    private javax.swing.JTextArea Ta_Descripciones;
    private javax.swing.JTextField Tb_Alias;
    private javax.swing.JTextField Tb_Cicatrices;
    private javax.swing.JTextField Tb_Estatura;
    private javax.swing.JTextField Tb_Nombre;
    private javax.swing.JTextField Tb_Tatuajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
