/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_de_denuncias;

import Conexion.Conexion;
import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author osiri
 */
public class InicioSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_alias = new javax.swing.JLabel();
        tb_alias = new javax.swing.JTextField();
        lb_contrasena = new javax.swing.JLabel();
        bt_aceptar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        lb_bienvenido = new javax.swing.JLabel();
        tb_contrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPanel1.setName(""); // NOI18N

        lb_alias.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lb_alias.setText("Alias");

        tb_alias.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        lb_contrasena.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lb_contrasena.setText("Contraseña");
        lb_contrasena.setToolTipText("");

        bt_aceptar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bt_aceptar.setText("Aceptar");
        bt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptar_Click(evt);
            }
        });

        bt_cancelar.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelar_Click(evt);
            }
        });

        lb_bienvenido.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lb_bienvenido.setText("Bienvenido a este Sistema de Denuncias");

        tb_contrasena.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(bt_aceptar)
                        .addGap(70, 70, 70)
                        .addComponent(bt_cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_alias)
                            .addComponent(lb_contrasena))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb_alias)
                            .addComponent(tb_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lb_bienvenido)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb_alias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_alias))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_contrasena)
                    .addComponent(tb_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_aceptar)
                    .addComponent(bt_cancelar))
                .addGap(21, 21, 21))
        );

        lb_alias.getAccessibleContext().setAccessibleName("label1");
        lb_alias.getAccessibleContext().setAccessibleDescription("");
        tb_alias.getAccessibleContext().setAccessibleName("TbAlias");
        lb_contrasena.getAccessibleContext().setAccessibleName("label2");
        bt_aceptar.getAccessibleContext().setAccessibleName("BtAceptar");
        bt_cancelar.getAccessibleContext().setAccessibleName("BtCancelar");
        tb_contrasena.getAccessibleContext().setAccessibleName("TbContrasena");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptar_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptar_Click
        // TODO add your handling code here:
        String alias = tb_alias.getText();
        String contrasena = new String(tb_contrasena.getPassword());
        if(alias.equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese el alias");        
        } else {
            if(contrasena.equals("")){JOptionPane.showMessageDialog(null, "Ingrese la contraseña");return;}
            //ArrayList<ArrayList<String>> dato = new ArrayList<ArrayList<String>>();
            
            /*Consultamos por el usuario logueado*/
            String consulta = "SELECT * FROM usuario where Alias='"+tb_alias.getText()+"' and contrasena= '"+contrasena+"';";
            
            ArrayList<ArrayList<String>> dato = Conexion.ejecutar_consulta(consulta);
            
            if(!dato.isEmpty()){
                frmPrincipal.MenuCuentaUsuario.setEnabled(true);
                frmPrincipal.MenuDenuncias.setEnabled(true);
                frmPrincipal.MenuSistema.setEnabled(true);
                this.dispose();
            } else{
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion, puede volver a intentar...");
            }

        }
    }//GEN-LAST:event_btAceptar_Click

    private void btCancelar_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelar_Click
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btCancelar_Click


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aceptar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_alias;
    private javax.swing.JLabel lb_bienvenido;
    private javax.swing.JLabel lb_contrasena;
    private javax.swing.JTextField tb_alias;
    private javax.swing.JPasswordField tb_contrasena;
    // End of variables declaration//GEN-END:variables
}
